# Generated by Django 4.1.3 on 2022-11-17 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="A brief description of the issue.", max_length=80),
                ),
                ("description", models.TextField(help_text="A detailed description of the issue.")),
                (
                    "state",
                    models.CharField(
                        choices=[("OPN", "Open"), ("CLS", "Closed")],
                        default="OPN",
                        help_text="The current state of the issue.",
                        max_length=3,
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        choices=[("OPN", "Open"), ("CLS", "Closed")],
                        default="OPN",
                        editable=False,
                        help_text="Previous state of the issue.",
                        max_length=3,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="A datetime of opening issue. Updated when the issue is moved to open state.",
                    ),
                ),
                (
                    "resolution_duration",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        help_text="The time in seconds the issue was in open state.",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        help_text="Assign a user to resolve this issue.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category best suited for the issue.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.category",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        help_text="The reporter of the issue.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
